import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import { api } from '../utils/api';

const Home: NextPage = () => {
	const hello = api.example.hello.useQuery({ text: 'from tRPC' });
	const users = api.example.getUsers.useQuery();

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1>{hello.data?.greeting}</h1>
				<Link href="/signup">Sign Up</Link>
				<ul>
					{users.data?.map((user) => (
						<li key={user.id}>{user.email}</li>
					))}
				</ul>
			</main>
		</>
	);
};

export default Home;
